"""NASDAQ universe from tastytrade instruments — snapshot-accumulation PIT.

tastytrade's GET /instruments/equities/active lists what is tradable TODAY;
there is no historical as-of query. So point-in-time membership is built the
honest way: snapshot the active list on a schedule (the daily loop), persist
each dated snapshot, and derive membership from the accumulated record.

Consequences, stated plainly:
- PIT coverage begins the day snapshots start accumulating — deep-history
  backtests remain survivorship-biased until enough snapshots exist (or a
  historical membership dataset is purchased later).
- From day one, though, the LIVE book's universe is exactly what is tradable
  at the broker — no symbol-mapping drift between data and execution.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pandas as pd


def fetch_active_equities(broker_or_client, listed_market: str = "XNAS",
                          per_page: int = 1000, max_pages: int = 30) -> list[dict]:
    """All active equities on `listed_market` right now. Accepts a
    TastytradeClient — or anything exposing `.request` or `.c.request`."""
    c = getattr(broker_or_client, "c", broker_or_client)
    out: list[dict] = []
    for page in range(max_pages):
        d = c.request("GET", "/instruments/equities/active",
                      params={"per-page": per_page, "page-offset": page})
        items = d.get("items", [])
        out += items
        if len(items) < per_page:
            break
    keep = []
    for it in out:
        if listed_market and it.get("listed-market") not in (listed_market, None):
            continue
        if it.get("is-options-only") or it.get("is-etf"):
            continue
        keep.append({"symbol": it.get("symbol"),
                     "listed_market": it.get("listed-market"),
                     "is_index": it.get("is-index", False),
                     "streamer_symbol": it.get("streamer-symbol", it.get("symbol"))})
    return [k for k in keep if k["symbol"] and not k["is_index"]]


def take_snapshot(broker_or_client, out_dir: str | Path,
                  listed_market: str = "XNAS") -> dict:
    """Persist today's active-equity snapshot (idempotent per day)."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    today = str(date.today())
    path = out_dir / f"{today}.json"
    if path.exists():
        return {"date": today, "symbols": len(json.loads(path.read_text())["symbols"]),
                "status": "exists"}
    eq = fetch_active_equities(broker_or_client, listed_market=listed_market)
    path.write_text(json.dumps({"date": today, "listed_market": listed_market,
                                "symbols": sorted(e["symbol"] for e in eq)}, indent=0))
    return {"date": today, "symbols": len(eq), "status": "written"}


def build_membership(snapshot_dir: str | Path) -> pd.DataFrame:
    """Daily boolean membership from all accumulated snapshots (ffilled)."""
    snapshot_dir = Path(snapshot_dir)
    snaps = sorted(snapshot_dir.glob("????-??-??.json"))
    if not snaps:
        raise FileNotFoundError(f"no snapshots in {snapshot_dir} — run take_snapshot first")
    rows = {}
    for p in snaps:
        js = json.loads(p.read_text())
        rows[pd.Timestamp(js["date"])] = set(js["symbols"])
    all_syms = sorted(set.union(*rows.values()))
    mem = pd.DataFrame(False, index=sorted(rows), columns=all_syms)
    for d, syms in rows.items():
        mem.loc[d, sorted(syms)] = True
    daily = mem.reindex(pd.bdate_range(mem.index[0], date.today())).ffill().fillna(False)
    return daily


def write_symbols_file(membership: pd.DataFrame, path: str | Path,
                       min_days_listed: int = 1) -> int:
    """Union of names ever seen (delisted history included once accumulated)."""
    days = membership.sum()
    keep = sorted(days[days >= min_days_listed].index)
    Path(path).write_text(
        "# generated by svyable.universe — tastytrade snapshot accumulation\n"
        + "\n".join(keep) + "\n")
    return len(keep)


def apply_membership(panel_close: pd.DataFrame,
                     membership: pd.DataFrame) -> pd.DataFrame:
    """Boolean mask aligned to a panel: tradable only while a member."""
    m = membership.reindex(index=panel_close.index, columns=panel_close.columns)
    return m.ffill().fillna(False)
